backend:
  name: github
  repo: erikkrieg/netlify-example
  branch: master

media_folder: static/assets

collections:
  - name: topic-pages
    label: Topic Pages
    folder: src/pages/topics
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "TopicPage" }
      - { label: "Title", name: "title", widget: "string" }
      - label: Topics
        name: topics
        widget: list
        fields: 
          - { label: Text, name: text, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Open In New Window, name: new-window, widget: boolean, default: false }
