backend:
  name: github
  repo: erikkrieg/netlify-example
  branch: master

media_folder: static/assets

collections:
  - name: topic-pages
    label: Topic Pages
    folder: src/pages/topics
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "TopicPage" }
      - { label: "Title", name: "title", widget: "string" }
      - label: Topics
        name: topics
        widget: list
        fields: 
          - { label: Text, name: text, widget: string }
          - { label: URL, name: url, widget: string }
      # - { label: "Publish Date", name: "date", widget: "datetime" }
      # - { label: "Description", name: "description", widget: "text" }
      # - { label: "Body", name: "body", widget: "markdown" }
